### ISSUE TITLE
Support for libfive_tree_render_slice

### ISSUE THREAD

**Issue by andybak** [zalo/libfive-unity#1]
Hi,

I've been trying to add support for libfive_tree_render_slice and libfive_tree_render_slice3 but I'm not experienced in interacting with native code. I understand the code for RenderMesh and tried basing it on this but I'm not clear how to get subsequent items in the libfive_contour or libfive_contours array. Would it be as simple as incrementing the pointer each time by the size of that item? 

What would the size of a contour point be?

**Comment by smilberger** [comment]
I wrote a Common Lisp binding for Libfive (called Tovero):

https://gitlab.com/kavalogic-inc/tovero

and have been (slowly) working on one for Python and Blender.

I wrapped both the slice and voxel functions from Libfive in Tovero:

![rocky-contours](https://user-images.githubusercontent.com/76091678/102316332-bc555600-3f43-11eb-9ff3-de498024b055.png)

![rocky-voxel](https://user-images.githubusercontent.com/76091678/102316344-c37c6400-3f43-11eb-9498-83ca98c85055.png)

I'm sure I can't help you with C# or Unity specifically, but the concept of slices is quite straightforward in Libfive.  The slice render just returns an array of polygons, corresponding to the set of closed 2D regions the current slicing plane intersects in the model.  You can then render this data as a polylines.  If you have any further questions about the low level API for this topic, you can follow up here.  Hope this helps a little.

**Comment by andybak** [comment]
It's been a while now but I think my question was about the size of a contour point in the datastructure (in bytes). I just needed to increment the pointer the right amount. I could probably have figured it out with trial and error but I got a little discouraged by the lack of response as it probably meant the chances of getting a PR accepted were low.

**Comment by smilberger** [comment]
I guess when you refer to "native" code, that means C.  The amount I know about C# would fit in a thimble, but looking at:

https://github.com/zalo/libfive-unity/blob/master/Assets/libfive/Scripts/LFMeshRendering.cs

in the function ```CompleteRenderLibFiveMesh``` it appears that you really don't have to know the size--it just uses array referencing (i.e. with ```[]``` bracket syntax) like in C once the returned mesh data is marshalled into the C# managed side.  The pointer syntax in the Libfive C structs can be treated like an array of the type it points to, with the element count stored as a separate integer value.

Sorry if you don't want to be "re-encouraged", but I was having a look at this project to see how I could improve my own binding--which have has been neglected for years.  Libfive is really nice, and I would like to see it in Blender as well as Unity so more people can use it.  The feedback from the GUI back to the model like in this Unity binding is something I would like to add to mine.

**Comment by zalo** [comment]
Apologies; I forgot to turn notifications on for issues to this repo. 🙃 

[The existing datastructures and functions can be viewed in libfive.cs.](https://github.com/zalo/libfive-unity/blob/master/Assets/libfive/Plugins/libfive.cs)

First thing's first make sure these are imported:
```csharp
using System.Runtime.InteropServices;
using libfivesharp.libFiveInternal;
```

By the looks of what's already been exposed in `libfive-unity`, `libfive_tree_render_slice` returns a pointer which can be marshaled into a `libfive_contours` struct, like this:
```csharp
IntPtr libFiveContoursPtr = libfive.libfive_tree_render_slice(tree, region, height, resolution);
libfive_contours libFiveContours = (libfive_contours)Marshal.PtrToStructure(libFiveContoursPtr, typeof(libfive_contours));
```

The "tricky" part, I suppose, was what you mentioned, marshalling the pointer-to-the-native-array-of-contours into a CSharp-array-of-contours:
```csharp
libfive_contour[] contours = new libfive_contour[libFiveContours.count];
for(int i = 0; i < contours.Length; i++){
  contours[i] = (libfive_contour)Marshal.PtrToStructure(libFiveContours.cs + (i * Marshal.SizeOf(typeof(libfive_contour)), typeof(libfive_contour));
}
```

Since each contour contains an array of points (which are themselves just floats), the fastest way to get them into CSharp would be to just copy the floats over wholesale (x and y interleaved):
```csharp
float[] contour0Floats = new float[contours[0].count * 2];
Marshal.Copy(contours[0].pts, contour0Floats, 0, contour0Floats.Length);
```

And then you can just deinterleave those in a for-loop:
```csharp
Vector2[] contour0 = new Vector2[contour0Floats.Length/2];
for(int j = 0; j < contour0.Length; j++){
  contour0[j] = new Vector2(contour0Floats[(j*2)], contour0Floats[(j*2)+1]);
}
```

And lastly, we delete the native memory (since we've successfully copied it all into managed memory):
```csharp
libfive.libfive_contours_delete(libFiveContoursPtr);
```
This prevents that native memory from sticking around forever (which is called a "memory leak").

I haven't tested any of this, but that's the general flow for rescuing data from pointers.
